### ISSUE TITLE
How to run the code about “for ali's subsample”?

### ISSUE THREAD

**Issue by kittykittyjiao** [abramhindle/bug-triager-scikit#2]
Hello. I find this web site from paper named "Crowdsourced Bug Triaging: Leveraging Q&A Platforms for Bug Assignment". I have cloned this code and run the code as the guide in README file. 
I run get-big.sh and got a very large number of issues about 20 projects from 2010 to 2018. However, I didn't find the dataset written on the paper. 
Therefore, Could you tell me about how to run this code with the dataset published on the paper?

**Comment by abramhindle** [comment]
Ali has links to the actual dataset:

    Hi Abram,
    The complete data set is in the repository:
    
        https://github.com/alisajedi/BugTriaging
    
    Specifically, they can see this path:
    
        https://github.com/alisajedi/BugTriaging/tree/master/Data/Input
    
    
    Best,
        Ali

**Comment by kittykittyjiao** [comment]
Hello,I download all the data from the web site you provide. The data file list as follows:
![image](https://user-images.githubusercontent.com/35564326/35268629-9d2a7d9e-0064-11e8-8adf-d1941f4c0807.png)
According to my understanding, the file named "issues2-forTop20Projects.tsv" is the data set for triaging which published on  "Crowdsourced Bug Triaging: Leveraging Q&A Platforms for Bug Assignment".
Then, I read all the file in bug-triager-scikit (the code written in python). I find that the data set for calculate kNN, SVM etc. is in JSON format, and the content and size are very different from "issues2-forTop20Projects.tsv".
So could you tell me how to use this data (issues2-forTop20Projects.tsv) to run these Python code (bug-triager-scikit)?

**Comment by abramhindle** [comment]
Here are the original files and output files https://archive.org/details/bug-triage-datas.tar

The https://github.com/abramhindle/bug-triager-scikit/tree/ali/data contains the makefile which shows how everything was run.

**Comment by kittykittyjiao** [comment]
Hello, I have three questions about the data downloaded from https://archive.org/details/bug-triage-datas.tar:
1. There is no issue data (small.json etc.) for project named "khan-exercises". could you send these data to me again?
2. The number of total issue for project named "gaia" only 33, while the number of issue in paper "Crowdsourced Bug Triaging: Leveraging Q&A Platforms for Bug Assignment" is 449. This is a big difference.
3.In the file named "small.csv", according to my understanding, "TotalIssues" means the total number of issues for each projects need to assigned, but what is the meaning of "AssignedIssues"? why the value of both is different?  I put a screenshot of project named "docker" as an example:
![image](https://user-images.githubusercontent.com/35564326/35336318-ff1d83a4-0152-11e8-8479-b536901e8e03.png)

**Comment by abramhindle** [comment]
Don't use small.csv. Read Ali's description in his data repo. 

Assigned Issues are issues that get assigned to people. Ground truth.

I cannot find the issue data for khan-exercises, ask Ali Sajedi.

**Comment by alisajedi** [comment]
Hi kittykittyjiao,
Please contact me at alisajedi@ualberta.ca
